terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
Command terminated by signal 6
	Command being timed: "/home/lseniukov/projects/nonative/GDR/build-nosuite-release/reconstructorTUM /home/lseniukov/hdd_scratch/datasets/rgbd_dataset_freiburg2_xyz /home/lseniukov/results/NO_SUITE_SPARSE/fr2_xyz_full/2 520.9 521.0 325.1 249.7 5000.0 irls.txt ba.txt gt.txt 2"
	User time (seconds): 11258.08
	System time (seconds): 849.09
	Percent of CPU this job got: 100%
	Elapsed (wall clock) time (h:mm:ss or m:ss): 3:21:40
	Average shared text size (kbytes): 0
	Average unshared data size (kbytes): 0
	Average stack size (kbytes): 0
	Average total size (kbytes): 0
	Maximum resident set size (kbytes): 98524476
	Average resident set size (kbytes): 0
	Major (requiring I/O) page faults: 0
	Minor (reclaiming a frame) page faults: 99867662
	Voluntary context switches: 274814
	Involuntary context switches: 49318
	Swaps: 0
	File system inputs: 142232412
	File system outputs: 166792
	Socket messages sent: 0
	Socket messages received: 0
	Signals delivered: 0
	Page size (bytes): 4096
	Exit status: 0
